#!/bin/bash
startTime=`date +%s%N`

curl -s 127.0.0.1:4000/[1-2500]/google.com >/dev/null &
curl -s 127.0.0.1:4000/[2500-5000]/google.com >/dev/null &
curl -s 127.0.0.1:4000/[5000-7500]/google.com >/dev/null &
curl -s 127.0.0.1:4000/[7500-10000]/google.com >/dev/null &

wait
endTime=`date +%s%N`
echo $(((endTime - startTime) / 1000000)) milliseconds
